### PR TITLE
Bug 1289636 - Add autoland to integration branches

### PR DESCRIPTION
**Pull request by EricRahm**

### CODE REVIEW

**Comment by EricRahm** [comment]
@wlach Can you take a look?

**Comment by wlach** [comment]
This looks good, have you tested it?

**Comment by EricRahm** [comment]
Yes the thing I was bisecting was successfully bisected.

**Comment by wlach** [comment]
Awesome, thanks! Will make a new release shortly.

**Comment by wlach** [comment]
There is a new release under https://github.com/mozilla/mozregression/releases with this fix.

**Pull request merged**
