### PR TITLE
Bug 1536013 - Select win64-aarch64 builds when appropriate.

### PR DESCRIPTION
**Pull request by KwanEsq**
Doing this to hopefully get a build for testing.

### CODE REVIEW

**Comment by KwanEsq** [comment]
@wlach ah, I was actually thinking that the proper way to do this would be to update mozinfo and push a new version of that first.  It should probably be returning 64 bits for ARM64, as it does for x86-64 even when running on 32-bit Python.  (It might also want to return aarch64 for processor instead of ARM64, ala x86_64 instead of AMD64)

**Comment by KwanEsq** [comment]
Thanks a lot for the collaborator add!
Now I just need to be careful I don't hit any new buttons...

**Comment by wlach** [comment]
@KwanEsq oh ok, if there's a more elegant fix involving mozinfo, let's go for that. I probably shouldn't review a patch for that, but can help with pushing that out to pypi once it's landed.

**Comment by wlach** [comment]
for now i'll do a new release of mozregression with the other fixes that are pending

**Comment by KwanEsq** [comment]
Whoops, pushed the wrong branch, didn't mean to do that yet.

**Pull request merged**
