### PR TITLE
ADBHost().devices() now raises ADBError instead of OSError

### PR DESCRIPTION
**Pull request by saru95**
According to https://bugzilla.mozilla.org/show_bug.cgi?id=1236469#c3

### CODE REVIEW

**Comment by parkouss** [comment]
Oh sorry @saru95 I somehow missed this PR, and now someone else is interested to work on the bug. If you want to work on mozregression, you're welcome, and we can discuss about it if you like!

**Comment by saru95** [comment]
Actually the tests didnt pass  so i closed it myself . I forgot to alter the tests . lol . anyway Ive worked on it and Ill be submitting a PR now . If the assignee addresses the issue , its fine ..ill close it  . :)

**Comment by parkouss** [comment]
Well usually it's best to say that you are working on it in the bugzilla bug, so this situation does not happen :) If you have something working, I will probable merge it though, and try to find another bug for the assignee quickly.
Regarding the bug, if you have any question, please ask!

**Comment by saru95** [comment]
Thanks for your help, btw I have filed a PR now .

**Pull request closed without merging**
