### PR TITLE
Misc gui

### PR DESCRIPTION
**Pull request by jpigree**
Multiple little tweaks to mozregression-gui.
In details:
- Add ArchLinux PyQt dev tools install steps
- Add subtitles to each wizard's pages
- Fix mozregression-gui name in ctrl-tab menu in gnome3

### CODE REVIEW

**Comment by jpigree** [comment]
Okay. I forced push to add your new changes on mozilla/master + the minor tweaks of the gui doc.

**Comment by jpigree** [comment]
Yeah, you are right. It seems to be a Qt Bug. I renamed it also because it seemed to me that an executable named with the application name was better than a main.py which is more a developer thing (main + .py).

I guess it is just my point of view. I understand that change the entry point like that is way too more impactful for such a minor bug.

I will try out your solution which I guess will work as a workaround.

**Comment by jpigree** [comment]
Needs some tests on windows though.

**Comment by parkouss** [comment]
Oh, I'm sorry I thought that you wanted to rename the whole application name. :) Now I get that it was only the file name that you wanted to rename!
Well I'm not against renaming that file, but it seemed that the cx freeze did not like it - maybe we can investigate this. Or we can just tweak the argv given to the application (maybe just removig the '.py' final part ?, or something like suggested above) and it will be good - I don't think that Qt cares about the file name (but maybe it cares about the file path).

**Comment by parkouss** [comment]
Awesome, thanks @jpigree !

**Pull request merged**
